### ISSUE TITLE
不能更新新立绘，切换到新卡池沙洲引路人 抽卡报错

### ISSUE THREAD

**Issue by thankU-ubi** [xulai1001/akgacha#8]
更新资源报错
[2022-07-06 18:47:34,839 akgacha] INFO: Message -1812790820 triggered update_pool.
- 更新res资源包...
D:\hoshinoBOT\HoshinoBot\hoshino\modules\akgacha\prtsres.py:38: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 38 of the file D:\hoshinoBOT\HoshinoBot\hoshino\modules\akgacha\prtsres.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(await r.text)
埃拉托not found！
多萝西not found！
承曦格雷伊not found！
星源not found！
埃拉托not found！
多萝西not found！
承曦格雷伊not found！
星源not found！

下面是抽卡报错

[2022-07-06 18:50:47,183 nonebot] INFO: Self: 2821521344, Message -314409631 from 609638635@[群:1006443456]: '[CQ:at,qq=2821521344] 方舟来一井'
[2022-07-06 18:50:47,184 akgacha] INFO: Message -314409631 triggered gacha_300.
{'star': 6, 'up': True, 'char': '多萝西'}
{'star': 6, 'up': True, 'char': '多萝西', 'rate_6': 12}
软保底 - 56
{'star': 6, 'up': False, 'char': '塞雷娅', 'rate_6': 18}
软保底 - 59
{'star': 6, 'up': True, 'char': '多萝西'}
{'star': 6, 'up': False, 'char': '麦哲伦', 'rate_6': 16}
软保底 - 58
{'star': 6, 'up': False, 'char': '铃兰'}
{'star': 6, 'up': True, 'char': '多萝西', 'rate_6': 30}
软保底 - 65
{'star': 6, 'up': False, 'char': '夜莺'}
[2022-07-06 18:50:47,445 akgacha] ERROR: <class 'KeyError'> occured when gacha_300 handling message -314409631.
[2022-07-06 18:50:47,446 akgacha] ERROR: None
Traceback (most recent call last):
  File "D:\hoshinoBOT\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\akgacha\__init__.py", line 149, in gacha_300
    await bot.send(ev, g.summarize(), at_sender=True)
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\akgacha\akgacha.py", line 273, in summarize
    pic = gen_team_pic(self.rare_list[6]) if not show_5star else gen_team_pic(self.rare_list[6] + self.rare_list[5])
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\akgacha\akgacha.py", line 85, in gen_team_pic
    rarity = char_data[char_id]["rarity"]
KeyError: None
[2022-07-06 18:50:47,451 nonebot] INFO: Message -314409631 is ignored: Handled by Hoshino

**Comment by xulai1001** [comment]
插件是通过抓取PRTS的卡池和干员数据来更新相关资源的。具体地址是
https://prts.wiki/w/%E5%8D%A1%E6%B1%A0%E4%B8%80%E8%A7%88/%E9%99%90%E6%97%B6%E5%AF%BB%E8%AE%BF
和
https://prts.wiki/w/%E5%B9%B2%E5%91%98%E4%B8%80%E8%A7%88
这两个地址通常会在游戏更新后1-2天完成更新。
如果这两个地址没有更新新卡池和头像，是抓取不到新干员的信息的，同时无法显示头像

我这里的测试，沙洲卡池是在7月6日约12点时开始可以抓到数据。可以重新尝试抓取。

**Comment by xulai1001** [comment]
已经推送新卡池数据。
https://github.com/xulai1001/akgacha/commit/f7b8fb96cff724cf97b7d6510c78e920719f2968

**Comment by xulai1001** [comment]
根据您的错误提示，如果自动更新资源仍然出错，可能是因为底层xml库不同导致的。
可以尝试根据错误提示，在BeautifulSoup的初始化参数里添加'features="lxml"试试看

更新资源的正确顺序是：
1，更新方舟基础数据（对应character_table.json）
2，更新方舟资源（对应res）
3，更新方舟卡池（对应config.json）
供参考！
